### ISSUE TITLE
new error 

### ISSUE THREAD

**Issue by dhrubo11** [Jeyaprabu/Unacademy-Downloader#2]
C:\Users\dhrub\Desktop\Unacademy-Downloader-master>Unac_down_main.py
Traceback (most recent call last):
  File "C:\Users\dhrub\Desktop\Unacademy-Downloader-master\Unac_down_main.py", line 9, in <module>
    import requests
ImportError: No module named requests

**Comment by Jeyaprabu** [comment]
Hi dhrubo,
its the same dependency,
you have to download the required modules
You have to install 'requests' module
refer [https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests](url)

**Comment by dhrubo11** [comment]
thnk you .now its working .. but can you make this script ..to convert audio and image into video file.

**Comment by Jeyaprabu** [comment]
Hi dhrubo,
Main motive is to have slides, videos we can download from Unacademy Youtube channel
Slides will be more useful while revision
Please share the utility so that everyone will be benefitted

**Comment by PavanRGowda** [comment]
Hello dhrubo,
Are you able to download the slides of the entire course completely?
If yes, please try for this url - [https://unacademy.com/lesson/overview-summary-of-class-viii-geography-ncert/UFV42OFG](url)
If you're able to download, please mail me the slides
Thank you

**Comment by Jeyaprabu** [comment]
Hi friends,
i have resolved the issue now
try with new updated code
