### ISSUE TITLE
Script not functioning as prescribed. Won't download all the slides of a course

### ISSUE THREAD

**Issue by PavanRGowda** [Jeyaprabu/Unacademy-Downloader#3]
The script won't download all the slides of a course from second video onwards whereas it downloads all the slides of the first video in the course. It just downloads only a single image or two from the second video in the course. 
PFA screenshot of the downloaded slides for better insights.
![screenshot from 2017-06-20 21-27-32](https://user-images.githubusercontent.com/12692361/27343004-4b8c0864-55ff-11e7-8b67-75e80e545f90.png)

From the above screenshot, you can see that all the slides of the first video in the course were downloaded whereas only one slide was downloaded from the second video till the last video in the course.

URL -  [https://unacademy.com/lesson/overview-summary-of-class-viii-geography-ncert/UFV42OFG](url)

Audio download is working well.

Please fix the bug as it might be of help to everyone. Thank you. I've become a fan of your work.

**Comment by Jeyaprabu** [comment]
Hi Pawan,
This was a good catch, 
thanks for taking your time to report the bug
**the utility will work for most of the courses without any issues**
I will try to resolve the issues as soon as possible
please share the utility with others so that everyone will get benefited
Thank You

**Comment by PavanRGowda** [comment]
Thanks for taking your time to develop this utility!
This utility will go on trending soon!
Please fix the above mentioned issue soon as might get more number of users.
For me, I've faced the same issue with all the courses I've tried.
I'll definitely share this utility as the audio download is working fine.
Please add video download option. It's a kind request from my side as it might help many aspirants. I know it's illegal but please consider my request.
Thanks again!

**Comment by Jeyaprabu** [comment]
Hi Pawan,
The utility seems to work for that course,
try now and enjoy the slides

**Comment by PavanRGowda** [comment]
Hello Jeyaprabhu,
The bug mentioned is not yet resolved.
Tried for the same url  -  [https://unacademy.com/lesson/overview-summary-of-class-viii-geography-ncert/UFV42OFG?source=Course](url)  and selected the option to download the entire course but it failed to produce expected results. 
Below is the screenshot of obtained output
![screenshot from 2017-06-22 20-50-56](https://user-images.githubusercontent.com/12692361/27442191-26f294ca-578d-11e7-9d3d-40b8fd31649e.png)

Please fix this
Also, every video of unacademy is not available in youtube so I kindly request you to add video download option
Thank you

**Comment by Jeyaprabu** [comment]
Hi Pawan,
try with updated code

**Comment by Jeyaprabu** [comment]
Hi, 
yeah i also observe this,
will resolve soon

**Comment by Jeyaprabu** [comment]
Hi,
Thanks pawan for your tip. I will try to utilise the iframe source
Anyway i have resolved the issue (atleast i hope)

**Comment by PavanRGowda** [comment]
There is still problem with JPEG images
Some JPEG are corrupt
![screenshot from 2017-06-23 00-01-24](https://user-images.githubusercontent.com/12692361/27449776-21892ca0-57a7-11e7-8ed8-5490e488bdc9.png)

Please take a look at this  - [https://stackoverflow.com/questions/38363276/image-scraped-as-html-page-with-urlretrieve](url)

**Comment by PavanRGowda** [comment]
Hi,
Did you fix the bug? Please update as it would benefit many aspirants. Thank you.

**Comment by Jeyaprabu** [comment]
Hi,
Will fix the issue this week.

**Comment by Jeyaprabu** [comment]
Hi, 
the utility is updated and now we can downloads without issues
