### ISSUE TITLE
Not able to download

### ISSUE THREAD

**Issue by AshishHere** [Jeyaprabu/Unacademy-Downloader#4]
![2017-07-04 11_28_46-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/29880368/27816923-2908286a-60ac-11e7-83e7-5086df7e851f.png)

Please look ... I am in urgent need of this script.. it worked few days back.. Thank you for this kind help.

**Comment by Jeyaprabu** [comment]
Hi, 
can you please mention the url that you have tried to download

**Comment by AshishHere** [comment]
https://unacademy.com/course/challenges-to-internal-security-of-india/18SSS47Y

https://unacademy.com/course/ethics-integrity-and-aptitude-gs-paper-iv/J8R4NE6O

These two I tried; I also randomly selected few links too.

Thanks for the prompt reply.

**Comment by PavanRGowda** [comment]
Hi Jeyaprabhu,
Even I'm facing the same problem.
After debugging, I found out that this line **img_link = re.search(".*(https://player-images.unacademy.link/.*/images/.{8}).*", data).group(1)** in image_link() function was the cause.
Regular expression is finding the required image link from the given URL or the response returned has different format compared to previous requests.
Here are the below screenshots to prove the same
![screenshot from 2017-07-05 00-40-03](https://user-images.githubusercontent.com/12692361/27841060-d30a4284-611b-11e7-8be1-1e89442eea33.png)
I've added a few print statements to find the line where script is going wrong
Below is the obtained output
![screenshot from 2017-07-05 00-40-35](https://user-images.githubusercontent.com/12692361/27841075-f40aae42-611b-11e7-9b20-96087eddc2ee.png)
Please ignore Beautifulsoup's Warning Messages.

**Comment by Jeyaprabu** [comment]
Hi,
I updated the utility
The issue is because unacademy website is evolving rapidly and image links are updated
Now utility works fine with above course link
And also you have to provide the lesson link not the course link
